name: Build
run-name: Build and Deploy
on:
  pull_request:
    types:
      - closed
    branches:
      - 'development'
  workflow_dispatch
permissions: write-all
jobs:
  push_to_pages:
    runs-on: ubuntu-latest
    name: Build Vue and Deploy
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'OsuDating-eu'
          reponame: 'OsuDating-Front_End'
          token: ${{ secrets.GITHUB_TOKEN }}
          useyarn: true