name: Build
run-name: Testing build with linter
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
          
      - name: Linter
        uses: borales/actions-yarn@v4
        with:
          cmd: lint # will run `yarn lint` command
          
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
